import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './styles/global.css'
import App from './App.jsx'

// Registers the service worker generated by vite-plugin-pwa (see
// vite.config.js). autoUpdate means a new version activates on next load
// without prompting — appropriate for a personal single-user app with no
// need for an update-available dialog.
registerSW({ immediate: true })

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
